### ISSUE TITLE
Needs update from study-template (not ruby-template)

### ISSUE THREAD

**Issue by payne-chris-r** [ga-wdi-boston/ruby-gem-study#20]
Leave ruby-template files out. Only update from study-template.

**Comment by laurenfazah** [comment]
All set

**Comment by gaand** [comment]
@jrhorn424 Should these update issues just be part of a process doc?

**Comment by jrhorn424** [comment]
@gaand I'm not sure. Some of these patterns are recordable. We should talk about some heuristics for choosing templates.

**Comment by gaand** [comment]
I claim that this commit a44327b7c479de3f63af2279492d0631bc53d067 closes this issue.

If we want to reopen issues or create new ones for updates, I'm okay with that but leaving an issue open forever doesn't to me seem like an issue but something else.
